"""Added descriptioin and datetime

Revision ID: 4a0e47dbf00d
Revises: c417394f0a8d
Create Date: 2026-01-02 12:36:03.637856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4a0e47dbf00d'
down_revision: Union[str, None] = 'c417394f0a8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('event', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('event', sa.Column('start_time', sa.Time(), nullable=True))
    op.add_column('event', sa.Column('end_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'end_time')
    op.drop_column('event', 'start_time')
    op.drop_column('event', 'date')
    op.drop_column('event', 'description')
    # ### end Alembic commands ###
